version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_USER: postgres
      POSTGRES_DB: mini_amazon
    restart: always
  web-init:
    build: ./web-app
    command: bash -c "./initserver.sh"
    volumes:
      - ./web-app:/code
    depends_on:
      - db
  web:
    build: ./web-app
    user: nobody
    command: /code/runserver.sh
    volumes:
      - ./web-app:/code
    expose:
      - "8000"
    depends_on:
      - web-init
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
    depends_on:
      - web
  server:
    build: ./server
    user: root
    volumes:
      - ./server:/code
    command: bash -c "./run.sh"
    ports:
      - "23456:23456" # for world
      - "9999:9999" # for web
      - "8888:8888" # for ups
    expose:
      - "23456"
    depends_on:
      - web

volumes:
  data-volume:
